RewriteEngine On

# Redireciona para index.php se o arquivo não existir
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]

# Define index.php como página padrão
DirectoryIndex index.php